apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: BackstageTest
  annotations:
    github.com/project-slug: Prasanna505/Backstage_test
spec:
  type: service 
  owner: user:guest
  lifecycle: experimental
